### ISSUE TITLE
Modificar variable rutaConfig

### ISSUE THREAD

**Issue by JuanPabloMF** [JFEspanolito/FindComments_PlatziCourse_UiPath#34]
He estado intentando usar el proyecto como se indica en el readme, sin embargo no logro realizar la instruccion "También debemos actualizar la ruta dentro de la sección de variables en la parte inferior, la Variable rutaConfig".

Aqui un screenshot de las variables que veo (en main.xaml y process.xaml)

![2020-08-16_02h18_26](https://user-images.githubusercontent.com/4017397/90328027-18dd4000-df67-11ea-92ae-4dd751bd811a.png)

Donde se encuentra esta variable o tenemos que crearla nosotros?

**Comment by JFEspanolito** [comment]
Hola Juan.
La variable in_ConfigFile es un argumento de entrada, lo que significa que es una variable que contiene la ruta del Excel de Config.
Dicha variable debe ser actualizada desde la siguiente ruta:
Main.xaml -> General Business Process -> Initialization -> Clic a First Run y en la sección de variables se mostrará la variable: 'rutaConfig'
Te dejo una pantalla de la ubicación.
![imagen](https://user-images.githubusercontent.com/6903502/90331016-24386780-df77-11ea-8d81-7738041c000c.png)

PD: gracias por la retro, intentaré clarificar más el readme.
